"""
ForexBot Strategy Engine (SLK + CRT + ABC/XYZ Multi-Timeframe Framework)
========================================================================
Institutional Price Action & Market Storyline Signal Generation Engine:
1. SLK (Structure, Liquidity, Key Level):
   - Market Environment: UPTREND, DOWNTREND, RANGING, CHOPPY
   - Market Phase: EXPANSION vs REVERSAL
   - Origin & Destination: Where price is coming from -> Where price is going
2. CRT (Candle Range Theory):
   - Candle High/Low sweep with candle closing back inside the range.
   - 3rd candle reaction from Key Levels (Open/Close, V-Shape, A-Shape, FVG, OB).
3. ABC (HTF Expectation) -> XYZ (LTF Execution):
   - HTF (Weekly / Daily / 4H / 2H) bias & liquidity sweep + breakout.
   - LTF (2H / 1H / 15M) London & New York session execution on disrespected
     key level flip into Imbalance (FVG) + Liquidity Sweep confirmation.
4. Risk/Reward:
   - Fixed Stop Loss: 50.0 pips
   - Fixed Take Profit: 150.0 pips (TP1) / 250.0 pips (TP2)
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Dict, Any, List, Tuple
import numpy as np
import pandas as pd

from config import (
    SUPPORTED_SYMBOLS,
    StrategyConfig,
    SessionConfig,
    SymbolSpec,
)


class SignalType(str, Enum):
    """Explicit trade action signal."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class MarketEnvironment(str, Enum):
    """Market structure regime."""
    UPTREND = "UPTREND"
    DOWNTREND = "DOWNTREND"
    RANGING = "RANGING"
    CHOPPY = "CHOPPY"


class MarketPhase(str, Enum):
    """Current price delivery phase."""
    EXPANSION = "EXPANSION"
    REVERSAL = "REVERSAL"
    CONSOLIDATION = "CONSOLIDATION"


class KeyLevelType(str, Enum):
    """Types of identified key price levels."""
    A_SHAPE_RESISTANCE = "A_SHAPE_RESISTANCE"  # Swing High / Resistance peak
    V_SHAPE_SUPPORT = "V_SHAPE_SUPPORT"        # Swing Low / Support valley
    OPEN_CLOSE_LEVEL = "OPEN_CLOSE_LEVEL"      # Horizontal Open/Close cluster
    FAIR_VALUE_GAP = "FAIR_VALUE_GAP"          # 3-candle imbalance (FVG)
    ORDER_BLOCK = "ORDER_BLOCK"                # Last opposing candle before displacement


@dataclass
class KeyLevel:
    """Represents a structural price key level."""
    level_type: KeyLevelType
    price: float
    high_boundary: float
    low_boundary: float
    timestamp: Any
    touches: int = 1
    is_disrespected: bool = False
    disrespected_time: Optional[Any] = None
    timeframe: str = "15m"


@dataclass
class CRTSweep:
    """Candle Range Theory (CRT) sweep event."""
    is_bullish_sweep: bool     # Swept low and closed back up inside range
    is_bearish_sweep: bool     # Swept high and closed back down inside range
    swept_level: float
    candle_time: Any
    timeframe: str
    target_liquidity: float


@dataclass
class MarketStoryline:
    """Complete multi-timeframe market state."""
    environment: MarketEnvironment
    phase: MarketPhase
    origin_liquidity: str      # Where price is coming from
    destination_liquidity: str # Where price is likely going next
    htf_bias: SignalType       # Expected directional bias (BUY / SELL / HOLD)
    rationale: str


@dataclass
class TradeSignal:
    """
    Structured container for trade signals generated by the strategy engine.
    """
    symbol: str
    signal: SignalType
    timestamp: Any
    entry_price: float
    stop_loss: float
    take_profit: float
    sl_pips: float
    tp_pips: float
    tp2_price: float
    tp2_pips: float
    lot_size: float
    rationale: str
    storyline: Optional[MarketStoryline] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_actionable(self) -> bool:
        """Returns True if signal is BUY or SELL."""
        return self.signal in (SignalType.BUY, SignalType.SELL)


# ---------------------------------------------------------------------------
# 1. Market Environment & Phase Classifier
# ---------------------------------------------------------------------------
class MarketEnvironmentClassifier:
    """
    Classifies market structure into Uptrend, Downtrend, Ranging, or Choppy,
    and identifies Expansion vs Reversal phases.
    """

    @staticmethod
    def classify(df: pd.DataFrame, lookback: int = 20) -> Tuple[MarketEnvironment, MarketPhase]:
        """
        Analyzes swing points, candle overlap, and momentum expansion.
        """
        if len(df) < lookback + 5:
            return MarketEnvironment.CHOPPY, MarketPhase.CONSOLIDATION

        recent = df.iloc[-lookback:].copy()
        highs = recent["high"].values
        lows = recent["low"].values
        opens = recent["open"].values
        closes = recent["close"].values

        # 1. Swing Highs & Lows detection
        swing_highs = []
        swing_lows = []
        for j in range(2, len(recent) - 2):
            if highs[j] > highs[j-1] and highs[j] > highs[j-2] and highs[j] > highs[j+1] and highs[j] > highs[j+2]:
                swing_highs.append(highs[j])
            if lows[j] < lows[j-1] and lows[j] < lows[j-2] and lows[j] < lows[j+1] and lows[j] < lows[j+2]:
                swing_lows.append(lows[j])

        # 2. Check Trend Direction (HH/HL vs LH/LL)
        is_uptrend = False
        is_downtrend = False

        if len(swing_highs) >= 2 and len(swing_lows) >= 2:
            hh = swing_highs[-1] > swing_highs[-2]
            hl = swing_lows[-1] > swing_lows[-2]
            lh = swing_highs[-1] < swing_highs[-2]
            ll = swing_lows[-1] < swing_lows[-2]

            if hh and hl:
                is_uptrend = True
            elif lh and ll:
                is_downtrend = True

        # 3. Check for Choppiness / Body Overlap
        candle_ranges = highs - lows
        avg_range = np.mean(candle_ranges) if len(candle_ranges) > 0 else 1e-5
        body_sizes = np.abs(closes - opens)
        avg_body = np.mean(body_sizes) if len(body_sizes) > 0 else 1e-5
        
        # Heavy wick / small body overlap indicates chop
        body_to_range_ratio = avg_body / avg_range if avg_range > 0 else 0

        # 4. Check for Expansion vs Reversal
        latest_candle_range = highs[-1] - lows[-1]
        latest_body = abs(closes[-1] - opens[-1])
        latest_expansion = (latest_body / latest_candle_range) >= 0.60 if latest_candle_range > 0 else False

        if is_uptrend:
            env = MarketEnvironment.UPTREND
            phase = MarketPhase.EXPANSION if (closes[-1] > opens[-1] and latest_expansion) else MarketPhase.CONSOLIDATION
        elif is_downtrend:
            env = MarketEnvironment.DOWNTREND
            phase = MarketPhase.EXPANSION if (closes[-1] < opens[-1] and latest_expansion) else MarketPhase.CONSOLIDATION
        elif body_to_range_ratio < 0.35:
            env = MarketEnvironment.CHOPPY
            phase = MarketPhase.CONSOLIDATION
        else:
            env = MarketEnvironment.RANGING
            phase = MarketPhase.CONSOLIDATION

        # Reversal detection: Latest candle swept a swing extreme and reversed
        if len(swing_highs) > 0 and highs[-1] > swing_highs[-1] and closes[-1] < opens[-1]:
            phase = MarketPhase.REVERSAL
        elif len(swing_lows) > 0 and lows[-1] < swing_lows[-1] and closes[-1] > opens[-1]:
            phase = MarketPhase.REVERSAL

        return env, phase


# ---------------------------------------------------------------------------
# 2. Key Level & Imbalance Detector
# ---------------------------------------------------------------------------
class KeyLevelDetector:
    """
    Identifies A-shape key levels (resistance), V-shape key levels (support),
    Open/Close levels, Fair Value Gaps (FVG), and Order Blocks (OB).
    """

    @staticmethod
    def find_a_shape_levels(df: pd.DataFrame, lookback: int = 30) -> List[KeyLevel]:
        """
        Finds A-shape resistance peaks that sponsored sells multiple times.
        """
        levels: List[KeyLevel] = []
        if len(df) < lookback:
            return levels

        sub_df = df.iloc[-lookback:].copy()
        highs = sub_df["high"].values
        lows = sub_df["low"].values
        times = sub_df["time"].values if "time" in sub_df.columns else sub_df.index.values

        for i in range(2, len(sub_df) - 2):
            if highs[i] >= highs[i-1] and highs[i] >= highs[i-2] and highs[i] >= highs[i+1] and highs[i] >= highs[i+2]:
                peak_price = highs[i]
                # Count how many subsequent bars tested this peak area (within 0.05% tolerance)
                tolerance = peak_price * 0.0008
                touches = 1
                disrespected = False
                disrespected_time = None

                for k in range(i + 1, len(sub_df)):
                    if abs(highs[k] - peak_price) <= tolerance:
                        touches += 1
                    if sub_df["close"].values[k] > peak_price + tolerance:
                        disrespected = True
                        disrespected_time = times[k]
                        break

                levels.append(KeyLevel(
                    level_type=KeyLevelType.A_SHAPE_RESISTANCE,
                    price=peak_price,
                    high_boundary=peak_price + tolerance,
                    low_boundary=peak_price - tolerance,
                    timestamp=times[i],
                    touches=touches,
                    is_disrespected=disrespected,
                    disrespected_time=disrespected_time
                ))
        return levels

    @staticmethod
    def find_v_shape_levels(df: pd.DataFrame, lookback: int = 30) -> List[KeyLevel]:
        """
        Finds V-shape support valleys that sponsored buys multiple times.
        """
        levels: List[KeyLevel] = []
        if len(df) < lookback:
            return levels

        sub_df = df.iloc[-lookback:].copy()
        highs = sub_df["high"].values
        lows = sub_df["low"].values
        times = sub_df["time"].values if "time" in sub_df.columns else sub_df.index.values

        for i in range(2, len(sub_df) - 2):
            if lows[i] <= lows[i-1] and lows[i] <= lows[i-2] and lows[i] <= lows[i+1] and lows[i] <= lows[i+2]:
                valley_price = lows[i]
                tolerance = valley_price * 0.0008
                touches = 1
                disrespected = False
                disrespected_time = None

                for k in range(i + 1, len(sub_df)):
                    if abs(lows[k] - valley_price) <= tolerance:
                        touches += 1
                    if sub_df["close"].values[k] < valley_price - tolerance:
                        disrespected = True
                        disrespected_time = times[k]
                        break

                levels.append(KeyLevel(
                    level_type=KeyLevelType.V_SHAPE_SUPPORT,
                    price=valley_price,
                    high_boundary=valley_price + tolerance,
                    low_boundary=valley_price - tolerance,
                    timestamp=times[i],
                    touches=touches,
                    is_disrespected=disrespected,
                    disrespected_time=disrespected_time
                ))
        return levels

    @staticmethod
    def find_fair_value_gaps(df: pd.DataFrame, min_pips: float, spec: SymbolSpec, lookback: int = 25) -> List[KeyLevel]:
        """
        Identifies Fair Value Gaps (3-candle imbalance).
        - Bullish FVG: Low[i] > High[i-2]
        - Bearish FVG: High[i] < Low[i-2]
        """
        fvgs: List[KeyLevel] = []
        if len(df) < 3:
            return fvgs

        sub_df = df.iloc[-lookback:].copy()
        highs = sub_df["high"].values
        lows = sub_df["low"].values
        times = sub_df["time"].values if "time" in sub_df.columns else sub_df.index.values
        min_delta = spec.pips_to_price_delta(min_pips)

        for i in range(2, len(sub_df)):
            # Bullish FVG
            if lows[i] > highs[i-2] + min_delta:
                fvgs.append(KeyLevel(
                    level_type=KeyLevelType.FAIR_VALUE_GAP,
                    price=(lows[i] + highs[i-2]) / 2.0,
                    high_boundary=lows[i],
                    low_boundary=highs[i-2],
                    timestamp=times[i-1]
                ))
            # Bearish FVG
            elif highs[i] < lows[i-2] - min_delta:
                fvgs.append(KeyLevel(
                    level_type=KeyLevelType.FAIR_VALUE_GAP,
                    price=(highs[i] + lows[i-2]) / 2.0,
                    high_boundary=lows[i-2],
                    low_boundary=highs[i],
                    timestamp=times[i-1]
                ))
        return fvgs


# ---------------------------------------------------------------------------
# 3. Candle Range Theory (CRT) Engine
# ---------------------------------------------------------------------------
class CandleRangeTheoryEngine:
    """
    Evaluates CRT sweeps:
    A candle sweeps the High or Low of the previous candle and closes BACK
    inside the previous candle's range (liquidity purge / failed continuation).
    """

    @staticmethod
    def evaluate_crt(df: pd.DataFrame, timeframe_name: str = "HTF") -> Optional[CRTSweep]:
        if len(df) < 2:
            return None

        prev_candle = df.iloc[-2]
        curr_candle = df.iloc[-1]

        prev_high = float(prev_candle["high"])
        prev_low = float(prev_candle["low"])
        prev_close = float(prev_candle["close"])
        prev_open = float(prev_candle["open"])

        curr_high = float(curr_candle["high"])
        curr_low = float(curr_candle["low"])
        curr_close = float(curr_candle["close"])
        curr_time = curr_candle.get("time", curr_candle.name)

        # Bullish CRT: Swept previous low, closed back ABOVE previous low / inside range
        bullish_sweep = (curr_low < prev_low) and (curr_close > prev_low)
        # Bearish CRT: Swept previous high, closed back BELOW previous high / inside range
        bearish_sweep = (curr_high > prev_high) and (curr_close < prev_high)

        if bullish_sweep:
            return CRTSweep(
                is_bullish_sweep=True,
                is_bearish_sweep=False,
                swept_level=prev_low,
                candle_time=curr_time,
                timeframe=timeframe_name,
                target_liquidity=prev_high
            )
        elif bearish_sweep:
            return CRTSweep(
                is_bullish_sweep=False,
                is_bearish_sweep=True,
                swept_level=prev_high,
                candle_time=curr_time,
                timeframe=timeframe_name,
                target_liquidity=prev_low
            )

        return None


# ---------------------------------------------------------------------------
# 4. Multi-Timeframe SLK Strategy Orchestrator
# ---------------------------------------------------------------------------
class PriceActionStrategy:
    """
    SLK (Structure, Liquidity, Key Level) + CRT + ABC/XYZ Multi-Timeframe Strategy.
    
    1. ABC (Expectation):
       - Identifies Market Environment (Uptrend/Downtrend/Range).
       - Evaluates HTF Liquidity Sweeps (Weekly/Daily/4H/2H CRT sweeps).
       - Confirms where price is coming from (Origin) and where it is going (Destination).
    2. XYZ (Execution):
       - Validates London & New York session trading hours.
       - Disrespected Key Level Model:
         * Bullish: An A-shape resistance level that sponsored sell(s) gets disrespected
           with an impulsive move leaving an FVG -> retests the level inside the FVG ->
           sweeps liquidity -> executes BUY.
         * Bearish: A V-shape support level that sponsored buy(s) gets disrespected
           with an impulsive move leaving an FVG -> retests the level inside the FVG ->
           sweeps liquidity -> executes SELL.
    3. Fixed SL = 50 pips, TP = 150 pips (TP1) & 250 pips (TP2).
    """

    def __init__(self, config: Optional[StrategyConfig] = None, session_config: Optional[SessionConfig] = None):
        self.config = config or StrategyConfig()
        self.session_config = session_config or SessionConfig()
        self.classifier = MarketEnvironmentClassifier()
        self.key_detector = KeyLevelDetector()
        self.crt_engine = CandleRangeTheoryEngine()

    def _validate_dataframe(self, df: pd.DataFrame) -> None:
        """Ensure required OHLCV columns exist."""
        required_cols = {"open", "high", "low", "close"}
        df_cols = {str(col).lower() for col in df.columns}
        missing = required_cols - df_cols
        if missing:
            raise ValueError(f"DataFrame is missing required OHLC columns: {missing}")

    def evaluate_multi_timeframe(
        self,
        symbol: str,
        ltf_df: pd.DataFrame,
        htf_df: Optional[pd.DataFrame] = None,
        weekly_df: Optional[pd.DataFrame] = None,
    ) -> TradeSignal:
        """
        Evaluates the full ABC -> XYZ multi-timeframe pipeline on the latest completed bar.
        """
        self._validate_dataframe(ltf_df)
        spec: SymbolSpec = SUPPORTED_SYMBOLS.get(symbol)
        if spec is None:
            raise KeyError(f"Symbol '{symbol}' is not configured in SUPPORTED_SYMBOLS.")

        data = ltf_df.copy()
        data.columns = [str(c).lower() for c in data.columns]
        
        latest_bar = data.iloc[-1]
        close = float(latest_bar["close"])
        timestamp = latest_bar.get("time", latest_bar.name)
        
        # Determine fixed lot size
        lot_size = spec.fixed_lot if self.config.USE_FIXED_LOT_SIZING else spec.min_lot

        # -------------------------------------------------------------------
        # Step 0: Session Timing Filter (London & New York Sessions Only)
        # -------------------------------------------------------------------
        if isinstance(timestamp, pd.Timestamp) or hasattr(timestamp, "hour"):
            is_active, session_name = self.session_config.is_session_active(timestamp)
            if not is_active:
                return self._hold_signal(
                    symbol, timestamp, close, lot_size,
                    f"Out of trading hours (Current: {session_name}). Trades only taken during London & New York sessions."
                )
        else:
            session_name = "SESSION_OK"

        # -------------------------------------------------------------------
        # Step 1: ABC (Expectation) - HTF Environment & Liquidity Bias
        # -------------------------------------------------------------------
        htf_data = htf_df if htf_df is not None and len(htf_df) >= 10 else data
        htf_env, htf_phase = self.classifier.classify(htf_data, lookback=20)
        
        # HTF CRT Sweep check
        htf_crt = self.crt_engine.evaluate_crt(htf_data, timeframe_name="HTF")
        
        # Weekly Liquidity Context if available
        weekly_bias = SignalType.HOLD
        if weekly_df is not None and len(weekly_df) >= 2:
            prev_w = weekly_df.iloc[-2]
            curr_w = weekly_df.iloc[-1]
            if float(curr_w["high"]) > float(prev_w["high"]):
                # Weekly high swept
                weekly_bias = SignalType.BUY if float(curr_w["close"]) > float(curr_w["open"]) else SignalType.SELL
            elif float(curr_w["low"]) < float(prev_w["low"]):
                weekly_bias = SignalType.SELL if float(curr_w["close"]) < float(curr_w["open"]) else SignalType.BUY

        # Establish Market Storyline
        if htf_crt and htf_crt.is_bullish_sweep:
            origin = f"HTF Low Sweep ({htf_crt.swept_level:.{spec.digits}f})"
            destination = f"HTF High Liquidity ({htf_crt.target_liquidity:.{spec.digits}f})"
            htf_bias = SignalType.BUY
            story_rationale = "HTF Bullish CRT Sweep: Low purged with strong close inside range -> targeting HTF highs."
        elif htf_crt and htf_crt.is_bearish_sweep:
            origin = f"HTF High Sweep ({htf_crt.swept_level:.{spec.digits}f})"
            destination = f"HTF Low Liquidity ({htf_crt.target_liquidity:.{spec.digits}f})"
            htf_bias = SignalType.SELL
            story_rationale = "HTF Bearish CRT Sweep: High purged with strong close inside range -> targeting HTF lows."
        elif htf_env == MarketEnvironment.UPTREND:
            origin = "Higher Low Demand"
            destination = "Previous Swing Highs / BSL"
            htf_bias = SignalType.BUY
            story_rationale = "HTF Uptrend Structure (HH/HL) expanding towards Buy-Side Liquidity."
        elif htf_env == MarketEnvironment.DOWNTREND:
            origin = "Lower High Supply"
            destination = "Previous Swing Lows / SSL"
            htf_bias = SignalType.SELL
            story_rationale = "HTF Downtrend Structure (LH/LL) expanding towards Sell-Side Liquidity."
        else:
            origin = "Range Equilibrium"
            destination = "Range Boundary"
            htf_bias = weekly_bias if weekly_bias != SignalType.HOLD else SignalType.HOLD
            story_rationale = f"Consolidation / Ranging environment with neutral bias."

        storyline = MarketStoryline(
            environment=htf_env,
            phase=htf_phase,
            origin_liquidity=origin,
            destination_liquidity=destination,
            htf_bias=htf_bias,
            rationale=story_rationale
        )

        # -------------------------------------------------------------------
        # Step 2: XYZ (Execution) - Disrespected Key Level + FVG + Sweep Model
        # -------------------------------------------------------------------
        a_levels = self.key_detector.find_a_shape_levels(data, lookback=40)
        v_levels = self.key_detector.find_v_shape_levels(data, lookback=40)
        fvgs = self.key_detector.find_fair_value_gaps(data, min_pips=self.config.MIN_FVG_PIPS, spec=spec, lookback=25)

        sl_pips = self.config.get_sl_pips(symbol)
        tp1_pips = self.config.get_tp_pips(symbol)
        tp2_pips = self.config.get_tp2_pips(symbol)

        sl_dist = spec.pips_to_price_delta(sl_pips)
        tp1_dist = spec.pips_to_price_delta(tp1_pips)
        tp2_dist = spec.pips_to_price_delta(tp2_pips)

        # LTF Liquidity Sweep Check on current completed candle
        ltf_crt = self.crt_engine.evaluate_crt(data, timeframe_name=self.config.TIMEFRAME_NAME)

        # -------------------------------------------------------------------
        # Bullish Model:
        # 1. A-shape key level used to sponsor sells (touches >= 1)
        # 2. Got disrespected to upside with impulsive move (leaving FVG)
        # 3. Current price pulled back into disrespected level / FVG
        # 4. LTF sweep of low / bullish reversal confirmation
        # -------------------------------------------------------------------
        for a_lvl in a_levels:
            if a_lvl.is_disrespected and a_lvl.touches >= 1:
                # Check if price is reacting in the zone of the disrespected level
                near_level = abs(close - a_lvl.price) <= (sl_dist * 0.4)
                # Check if there is an overlapping or nearby FVG
                has_fvg_confluence = any(
                    (fvg.low_boundary <= a_lvl.price <= fvg.high_boundary) or
                    (fvg.low_boundary <= close <= fvg.high_boundary)
                    for fvg in fvgs
                )

                # LTF confirmation sweep or bullish candle rejection
                candle_bullish = float(latest_bar["close"]) > float(latest_bar["open"])
                ltf_low_swept = (ltf_crt is not None and ltf_crt.is_bullish_sweep) or (float(latest_bar["low"]) < float(data.iloc[-2]["low"]) and candle_bullish)

                if (near_level or has_fvg_confluence) and ltf_low_swept and candle_bullish:
                    entry_p = spec.round_price(close)
                    sl_p = spec.round_price(entry_p - sl_dist)
                    tp1_p = spec.round_price(entry_p + tp1_dist)
                    tp2_p = spec.round_price(entry_p + tp2_dist)

                    return TradeSignal(
                        symbol=symbol,
                        signal=SignalType.BUY,
                        timestamp=timestamp,
                        entry_price=entry_p,
                        stop_loss=sl_p,
                        take_profit=tp1_p,
                        sl_pips=sl_pips,
                        tp_pips=tp1_pips,
                        tp2_price=tp2_p,
                        tp2_pips=tp2_pips,
                        lot_size=lot_size,
                        rationale=(
                            f"SLK Bullish Execution [{session_name}]: Disrespected A-Shape Resistance "
                            f"({a_lvl.price:.{spec.digits}f}, {a_lvl.touches} touches) retested inside FVG + "
                            f"LTF Low Liquidity Sweep confirmation. Targeting {storyline.destination_liquidity}."
                        ),
                        storyline=storyline,
                        metadata={
                            "session": session_name,
                            "key_level_type": a_lvl.level_type.value,
                            "key_level_price": a_lvl.price,
                            "key_level_touches": a_lvl.touches,
                            "fvg_confluence": has_fvg_confluence,
                            "environment": htf_env.value,
                            "phase": htf_phase.value,
                        }
                    )

        # -------------------------------------------------------------------
        # Bearish Model:
        # 1. V-shape key level used to sponsor buys (touches >= 1)
        # 2. Got disrespected to downside with impulsive move (leaving FVG)
        # 3. Current price pulled back into disrespected level / FVG
        # 4. LTF sweep of high / bearish reversal confirmation
        # -------------------------------------------------------------------
        for v_lvl in v_levels:
            if v_lvl.is_disrespected and v_lvl.touches >= 1:
                near_level = abs(close - v_lvl.price) <= (sl_dist * 0.4)
                has_fvg_confluence = any(
                    (fvg.low_boundary <= v_lvl.price <= fvg.high_boundary) or
                    (fvg.low_boundary <= close <= fvg.high_boundary)
                    for fvg in fvgs
                )

                candle_bearish = float(latest_bar["close"]) < float(latest_bar["open"])
                ltf_high_swept = (ltf_crt is not None and ltf_crt.is_bearish_sweep) or (float(latest_bar["high"]) > float(data.iloc[-2]["high"]) and candle_bearish)

                if (near_level or has_fvg_confluence) and ltf_high_swept and candle_bearish:
                    entry_p = spec.round_price(close)
                    sl_p = spec.round_price(entry_p + sl_dist)
                    tp1_p = spec.round_price(entry_p - tp1_dist)
                    tp2_p = spec.round_price(entry_p - tp2_dist)

                    return TradeSignal(
                        symbol=symbol,
                        signal=SignalType.SELL,
                        timestamp=timestamp,
                        entry_price=entry_p,
                        stop_loss=sl_p,
                        take_profit=tp1_p,
                        sl_pips=sl_pips,
                        tp_pips=tp1_pips,
                        tp2_price=tp2_p,
                        tp2_pips=tp2_pips,
                        lot_size=lot_size,
                        rationale=(
                            f"SLK Bearish Execution [{session_name}]: Disrespected V-Shape Support "
                            f"({v_lvl.price:.{spec.digits}f}, {v_lvl.touches} touches) retested inside FVG + "
                            f"LTF High Liquidity Sweep confirmation. Targeting {storyline.destination_liquidity}."
                        ),
                        storyline=storyline,
                        metadata={
                            "session": session_name,
                            "key_level_type": v_lvl.level_type.value,
                            "key_level_price": v_lvl.price,
                            "key_level_touches": v_lvl.touches,
                            "fvg_confluence": has_fvg_confluence,
                            "environment": htf_env.value,
                            "phase": htf_phase.value,
                        }
                    )

        # -------------------------------------------------------------------
        # Fallback CRT & Structural Breakout Model (Within Session)
        # -------------------------------------------------------------------
        if ltf_crt is not None:
            if ltf_crt.is_bullish_sweep and htf_bias in (SignalType.BUY, SignalType.HOLD):
                entry_p = spec.round_price(close)
                sl_p = spec.round_price(entry_p - sl_dist)
                tp1_p = spec.round_price(entry_p + tp1_dist)
                tp2_p = spec.round_price(entry_p + tp2_dist)

                return TradeSignal(
                    symbol=symbol,
                    signal=SignalType.BUY,
                    timestamp=timestamp,
                    entry_price=entry_p,
                    stop_loss=sl_p,
                    take_profit=tp1_p,
                    sl_pips=sl_pips,
                    tp_pips=tp1_pips,
                    tp2_price=tp2_p,
                    tp2_pips=tp2_pips,
                    lot_size=lot_size,
                    rationale=f"CRT Bullish Sweep [{session_name}]: Low swept ({ltf_crt.swept_level:.{spec.digits}f}) with close inside range. Storyline: {storyline.rationale}",
                    storyline=storyline,
                    metadata={"trigger": "CRT_SWEEP_BUY", "session": session_name}
                )
            elif ltf_crt.is_bearish_sweep and htf_bias in (SignalType.SELL, SignalType.HOLD):
                entry_p = spec.round_price(close)
                sl_p = spec.round_price(entry_p + sl_dist)
                tp1_p = spec.round_price(entry_p - tp1_dist)
                tp2_p = spec.round_price(entry_p - tp2_dist)

                return TradeSignal(
                    symbol=symbol,
                    signal=SignalType.SELL,
                    timestamp=timestamp,
                    entry_price=entry_p,
                    stop_loss=sl_p,
                    take_profit=tp1_p,
                    sl_pips=sl_pips,
                    tp_pips=tp1_pips,
                    tp2_price=tp2_p,
                    tp2_pips=tp2_pips,
                    lot_size=lot_size,
                    rationale=f"CRT Bearish Sweep [{session_name}]: High swept ({ltf_crt.swept_level:.{spec.digits}f}) with close inside range. Storyline: {storyline.rationale}",
                    storyline=storyline,
                    metadata={"trigger": "CRT_SWEEP_SELL", "session": session_name}
                )

        return self._hold_signal(symbol, timestamp, close, lot_size, "No SLK or CRT entry criteria met", storyline)

    def evaluate_latest(self, df: pd.DataFrame, symbol: str) -> TradeSignal:
        """Single-timeframe evaluation wrapper compatible with live loop & test runners."""
        return self.evaluate_multi_timeframe(symbol, ltf_df=df)

    def _hold_signal(
        self,
        symbol: str,
        timestamp: Any,
        close: float,
        lot_size: float,
        rationale: str,
        storyline: Optional[MarketStoryline] = None
    ) -> TradeSignal:
        """Helper to create a neutral HOLD signal."""
        sl_pips = self.config.get_sl_pips(symbol)
        tp_pips = self.config.get_tp_pips(symbol)
        tp2_pips = self.config.get_tp2_pips(symbol)
        return TradeSignal(
            symbol=symbol,
            signal=SignalType.HOLD,
            timestamp=timestamp,
            entry_price=close,
            stop_loss=0.0,
            take_profit=0.0,
            sl_pips=sl_pips,
            tp_pips=tp_pips,
            tp2_price=0.0,
            tp2_pips=tp2_pips,
            lot_size=lot_size,
            rationale=rationale,
            storyline=storyline,
            metadata={}
        )

    def generate_all_signals(self, df: pd.DataFrame, symbol: str) -> pd.DataFrame:
        """
        Batch processing of an entire historical DataFrame for backtesting.
        Adds signal columns: ['signal', 'entry_price', 'stop_loss', 'take_profit', 'lot_size'].
        """
        self._validate_dataframe(df)
        data = df.copy()
        data.columns = [str(c).lower() for c in data.columns]
        
        signals = []
        entry_prices = []
        stop_losses = []
        take_profits = []
        lot_sizes = []

        lookback = self.config.SWING_LOOKBACK
        spec = SUPPORTED_SYMBOLS[symbol]
        lot_size = spec.fixed_lot if self.config.USE_FIXED_LOT_SIZING else spec.min_lot

        for i in range(len(data)):
            if i < lookback + 5:
                signals.append(SignalType.HOLD.value)
                entry_prices.append(0.0)
                stop_losses.append(0.0)
                take_profits.append(0.0)
                lot_sizes.append(lot_size)
                continue

            sub_df = data.iloc[:i+1]
            sig = self.evaluate_latest(sub_df, symbol)
            signals.append(sig.signal.value)
            entry_prices.append(sig.entry_price)
            stop_losses.append(sig.stop_loss)
            take_profits.append(sig.take_profit)
            lot_sizes.append(sig.lot_size)

        data["signal"] = signals
        data["entry_price"] = entry_prices
        data["stop_loss"] = stop_losses
        data["take_profit"] = take_profits
        data["lot_size"] = lot_sizes
        return data

